# Generated by Django 5.2.6 on 2025-10-02 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('request_data', models.JSONField()),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField()),
                ('response_timestamp', models.DateTimeField(auto_now=True)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Query Log',
                'verbose_name_plural': 'User Query Logs',
                'ordering': ['-request_timestamp'],
            },
        ),
    ]
